### ISSUE TITLE
How to setup this?

### ISSUE THREAD

**Issue by Code-Crash** [NodeGeeks/loopback-connector-quickbooks#1]
Hi @TeknoloGenie ,

I don't have much idea about QuickBooks and QuickBooks Web Connector, Can you guide me how to setup this, I have my QuickBooks file ready and I also have web connector, But I don't know where to setup this code, its compulsory to add this code on the same system where QuickBooks already install or we can add this anywhere on the server?

Thanks

**Comment by TeknoloGenie** [comment]
Hi @Code-Crash 

Thanks for showing interest in the project, the `readme` explains how to setup the connector in the `datasources.json` file within your `loopback` project. Because im still making massive code changes daily i am waiting until this is ready for use in a production environment before releasing a more detailed setup guide. As of right now though this Connector isn't safe to run against real world data yet. You can expect v1.0.0-beta to be released sometime mid Nov, which will be the version that i would be satisfied with before spending time creating `documentation` for this connector. In the mean time, take a look at the readme, study up on how to [setup QBWC](https://developer-static.intuit.com/qbSDK-current/doc/PDF/QBWC_proguide.pdf)

**Comment by Code-Crash** [comment]
Hey @TeknoloGenie Thanks for the response.

One more question
It is necessary that this project and the QuickBooks will be on the same system or we can handle this by remote also?

**Comment by TeknoloGenie** [comment]
Yeah sorry about that i was just editing my prev comment with the answer to that question, currently it can be on a remote server but you would need to setup the HTTPS protocals and generate the self signed certificates required in order to allow the communication, and even at that i HIGHLY DO NOT suggest using this over remote public server until this is ready for production use. If i were you or anyone else i would run this on the same machine running quickbooks, OR if your on a local network assign the `AppURL` attribute in your `.QWC` file to the local ip address of the workstation running your loopback api.

Hope that answers your question.

**Comment by Code-Crash** [comment]
Thanks, @TeknoloGenie . I got my answer :) 

I understand that this is not ready for production yet but as I'm working on the QBWC so I will also try to participate in this project. :)

**Comment by TeknoloGenie** [comment]
@Code-Crash How's it coming along with using this in your `loopback api`? I plan on starting the development of a more robust, scalable connector sometime this weekend and should finish up before the 1st of Dec with a stable release that is worthy of production use. Would you be interested in getting assigned some tasks to help out?

**Comment by Code-Crash** [comment]
@TeknoloGenie I appreciate you are asking me :) .

Yesterday, I was able to connect my QuickBooks company file by using the QBWC and [johnballantyne/qbws](https://github.com/johnballantyne/qbws) which you are using in your project, today if I will get time then try to connect my company file and SOAP service on the local system with your project.

So I'm ready but as I don't have much experience in this thing just provide me the guidelines and we can go together.

**Comment by TeknoloGenie** [comment]
Closing this in reference to `commit `https://github.com/NodeGeeks/loopback-connector-quickbooks/commit/9a631eea378750ed9d496631b84739ae68cdea31 where i uploaded example usage.
