### ISSUE TITLE
QuickBooks found an error when parsing the provided XML text stream

### ISSUE THREAD

**Issue by Code-Crash** [NodeGeeks/loopback-connector-quickbooks#14]
Hi @TeknoloGenie ,

When I run the service and web connector, I have put the console for arguments in `receiveResponseXML(args)` and I get the following response:

```
{ ticket: '{2383efae-c4fb-41ea-b1b4-0666e71c5836}',
response: '',
hresult: '0x80040400',
message: 'QuickBooks found an error when parsing the provided XML text stream.' }
```

and It's coming after performing `sendRequestXML()`.

have a look when you will find a time.

**Comment by TeknoloGenie** [comment]
@Code-Crash , Thanks for creating a new issue for [what we discussed about your malformed XMLRequests](https://github.com/NodeGeeks/loopback-connector-quickbooks/issues/7#issuecomment-262792953). 

1st, we're you able to grab the entire XMLRequest object that gets built? I [commented here](https://github.com/NodeGeeks/loopback-connector-quickbooks/issues/7#issuecomment-262942045) where to find it being returned in the `buildXMLRequest` method? Solving your issue is simple, it's finding out what's wrong is the hard part lol. 

You should read up on [this FAQ page about qbXML](http://www.consolibyte.com/docs/index.php/QbXML_FAQ) it really helped me gain an understanding of things during the short time period of time I had to develop this. There's quite a bit I learned from the [`consolibyte/quickbooks-php`](https://github.com/consolibyte/quickbooks-php) even more recently. 

You can try and fix this issue yourself, or you could also just setup the testing grounds for me to test your code against the latest release. I can have the issue resolved by the 2nd.

If you want to dive in yourself use the XML validator that comes with the QuickBook SDK that you should have installed before installing your Web Connector. Or by comparing the generated qbXML file to the XML request files found on the [OSR Documentation website](https://developer-static.intuit.com/qbSDK-current/Common/newOSR/index.html) .

By taking the dynamically built XMLRequest object and copying it into the validator you will find out WHY you're having this issue. It's probably a simple fix that I overlooked. I really need to sit down and before continuing development on this I must spend time and create `test scripts` for what functionality is done.

Again... long comment, and lots of reading if you want to help with the `dev` side of things instead of the `testing` side of things. However, if you want to stick with the testing and let me handle the dev I'm fine with that. Just keep them issues coming :). I have to perfect this and have it ready for production use in order to utilize this connector in a new SaaS product launching by Jan 1st (owned and built by me). I appreciate your help. And I'll get this resolved ASAP!

@JeremyARussell & @shuety719 - tagged to get you guys involved, could use your feedback, idea's and production requirements.

**Comment by Code-Crash** [comment]
@TeknoloGenie  Thanks for heads up, Yes I love to help with `dev` side. I'm also currently stuck with my other project, but I will try to get the things ready for this project.

**Comment by Code-Crash** [comment]
@TeknoloGenie You are right, I found 

```
<?xml version="1.0"?>
<?qbxml version="13.0"?>
<QBXML>
  <QBXMLMsgsRq onError="stopOnError">
    <QBEmployeeQueryRq requestID="QBEmployee">
      <OwnerID>0</OwnerID>
    </QBEmployeeQueryRq>
  </QBXMLMsgsRq>
</QBXML>
```

and as per [OSR Document Website](https://developer-static.intuit.com/qbSDK-current/Common/newOSR/index.html) the will be 

```
<?xml version="1.0" encoding="utf-8"?>
<?qbxml version="13.0"?>
<QBXML>
  <QBXMLMsgsRq onError="stopOnError">
    <EmployeeQueryRq requestID="Employee">
      <OwnerID>0</OwnerID>
    </QBEmployeeQueryRq>
  </QBXMLMsgsRq>
</QBXML>
```


Here is the only one main difference is as `QBEmployeeQueryRq` should be `EmployeeQueryRq`, 

So When I modify that its working fine.
But before creating pull request I need to know is there any specific reason to append the QB to each model?

or should I remove that code and create a PR?
also I added a `encoding="utf-8"? ` while building request.

**Comment by TeknoloGenie** [comment]
Oh wow, so yeah this really proves my point on the fact that I really should have Continuous Integration/Development techniques implemented that follow the same guidelines StrongLoop does within their connectors, more specifically their `Contribution Guidelines`.  

Feeling foolish to have out in the open. I'm not a very agile guy and definitely been working on my agile methods.  #1 priority is definitely revamping this entire repository tomorrow, followed by new features and fixes on the 2nd. So if you have any requests speak now lol. I will go ahead and implement the proper code reviews and setup automated tests tomorrow if not today. There's a massive need for the connector and I do not want to start publishing it out there like crazy until I get this mess cleaned up and prevent this from happening again. I created issue #17 to get that into the list of thigs to do during the 2-3 days I'll spend finishing this project off to a point where its production ready.

About this particular issue regarding the reason why `QB` was added to model names goes back to becoming a widely supported project backed by massive Loopback community that has been established, maybe even if done right pass the torch onto Strongloop to have them take it over. Most, in order to do that I need to ensure that this connector would not conflict with any previous existing models due to the goals in refactoring set out in issue #4 

I'm going to go ahead and close this issue out and I will push a fix for this immediately to get you going. Sorry to have wasted so much of your time. 

I've created issue #16 to get that going. It's going to be a top priority and I'll add a description to it shortly but just briefly as its late and I must take a nap lol. Probably why I made this mistake in the first place (sleep coding lol). Either way, the next release will be a complete overhaul of the project. Keep these issues coming, great work @Code-Crash !

**Comment by Code-Crash** [comment]
@TeknoloGenie How you manage to write this much? :P ,  Well it's fine :) 

So before creating/revamping this project, please make sure to handle the multiple company files, 
You can do this by creating an each users credentials with their company file information and create a session for each user and according to the user handle the request.

I'm not sure how you would plan for this, but I'm excited to see the new changes. 👍
